### ISSUE TITLE
Issue in line 7 app.js

### ISSUE THREAD

**Issue by 0x61656c** [tambatd/ThingsThatMakeMeHappy#1]
looks like there is an issue in the array declaration on line 7 here: src/App.js 

You should be able to fix by adding this line right below:

ThingsThatMakeMeHappy.push("beans as a global reserve currency");

**Comment by tambatd** [comment]
🅱️eans have 🅱️een added

![image](https://user-images.githubusercontent.com/54927248/145666704-e0cae198-5710-41c0-bb84-95df07b59567.png)
